definitions:
  email.EmailTextContent:
    properties:
      content:
        description: 消息体
        type: string
      id:
        type: integer
      mail_cc:
        description: 抄送
        type: string
      mail_from:
        description: 发送者
        type: string
      mail_to:
        description: 接受者
        type: string
      subject:
        description: 主题
        type: string
      twf_created:
        $ref: '#/definitions/jsonTime.JSONTime'
      twf_modified:
        $ref: '#/definitions/jsonTime.JSONTime'
    type: object
  jsonTime.JSONTime:
    properties:
      time.Time:
        type: string
    type: object
info:
  contact:
    email: mustang2247@gmail.com
    name: Mustang Kong
  title: golang-common-base API docs
  version: 0.0.1
paths:
  /api/v1/email/add:
    post:
      consumes:
      - application/json
      description: 添加 email 数据到数据库
      parameters:
      - description: 新建email数据
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/email.EmailTextContent'
      produces:
      - application/json
      responses:
        "0":
          description: ""
      summary: 添加 email 数据到数据库
      tags:
      - email
  /api/v1/email/delete/:contentId:
    delete:
      consumes:
      - application/json
      description: 删除 email 数据
      produces:
      - application/json
      responses:
        "0":
          description: '{"code":0,"message":"删除email成功","data":"32"}'
          schema:
            type: string
      summary: 删除 email 数据
      tags:
      - email
  /api/v1/email/list:
    get:
      consumes:
      - application/json
      description: 获取 email 列表
      parameters:
      - description: 获取第几页的数据，默认为：1
        in: query
        name: page
        type: integer
      - description: 每页展示多少行，默认为：10
        in: query
        name: page_size
        type: integer
      - description: 按照倒序或者顺序的方式排列，0或者-1为倒序，其他值为顺序
        in: query
        name: sort
        type: integer
      produces:
      - application/json
      responses:
        "0":
          description: '{"code":0,"message":"获取分类列表成功","data":{}}'
          schema:
            type: string
      summary: 获取 email 列表
      tags:
      - email
  /api/v1/email/push:
    post:
      consumes:
      - application/json
      description: 推送 email 数据到数据库
      parameters:
      - description: 新建email数据
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/email.EmailTextContent'
      produces:
      - application/json
      responses:
        "0":
          description: ""
      summary: 推送 email 数据到数据库
      tags:
      - email
  /api/v1/email/update:
    put:
      consumes:
      - application/json
      description: "更新分类\t{\"name\":\"test1234\",\"key\":\"mus_test\",\"child\":{\"0-\":\"test\"}}\""
      parameters:
      - description: 更新email数据
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/email.EmailTextContent'
      produces:
      - application/json
      responses:
        "0":
          description: '{"code":0,"message":"更新email 数据成功","data":"32"}'
          schema:
            type: string
      summary: 更新 email 数据
      tags:
      - email
swagger: "2.0"
